Feature request: Extend wilayaProjection to project nested fields
dzcode-io/leblad pull request #28
Opened 2020-10-01 14:24 UTC by InternetRamen

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Extended wilayaProjection to project nested fields.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] This change requires a documentation update

# Checklist:

- [ X ] I checked that there's no dataset update (can be done by running `npm run update-dataset`)
- [ X ] `npm test` passes on my machine
- [ X ] `npm run lint` passes on my machine

My friend @makeBread helped me with this.

2020-10-01 14:25 UTC, InternetRamen commented
I don't know how to fix 6 eslint errors.

2020-10-01 21:20 UTC, Fcmam5 commented
Thank you @InternetRamen and @makeBread ! You got this ESLINT error as we are using a [sonarjs plugin for ESLINT](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md) and that flagged that your function is hard to read > hard to maintain.

I believe that we can do it in a better and a fancy way, I can help you with it, we can have a call where we share our screen and code it together 😄 , does this sound good for you?

2020-10-01 21:21 UTC, Fcmam5 requested changes
Thank you @InternetRamen and @makeBread ! You got this ESLINT error as we are using a [sonarjs plugin for ESLINT](https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/docs/rules/cognitive-complexity.md) and that flagged that your function is hard to read > hard to maintain.

I believe that we can do it in a better and a fancy way, I can help you with it, we can have a call where we share our screen and code it together 😄 , does this sound good for you?

2020-10-02 01:16 UTC, InternetRamen commented
@Fcmam5 I'm not sure I would be able to call as my coding times are unpredictable based on my school work. Are there any main improvements that could be added to the code?

2020-10-04 19:36 UTC, InternetRamen commented
@Fcmam5

2020-10-04 21:57 UTC, Fcmam5 commented
This code is too complex, and that's why ESLINT reported a ` Cognitive Complexity` error. I'm looking for a library (or probably create one) that makes it easier to do this. I will get back to you as soon as I find something.

2020-10-04 22:15 UTC, InternetRamen commented
@Fcmam5 Alright, thank you!

2021-03-26 01:42 UTC, closed without merging